apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cigg-app-database-statefulset
  namespace: cigg-app
spec:
  selector:
    matchLabels:
      app: cigg-app-database
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: cigg-app-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: cigtracker
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: cigtracker
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
