apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cigg-app.fullname" . }}-db-migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    # 🔴 Temporarily removed delete policy for debugging
    # "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 4

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: flyway
          image: {{ .Values.migration.image }}

          command: ["/bin/sh", "-c"]

          args:
            - |
              echo "Waiting for DB...";
              sleep 20;

              flyway \
              -url={{ .Values.migration.jdbcUrl }} \
              -user="$DB_USER" \
              -password="$DB_PASSWORD" \
              -locations=filesystem:/flyway/sql \
              -connectRetries=60 \
              migrate

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "cigg-app.fullname" . }}-secrets
                  key: DB_USER_APP

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cigg-app.fullname" . }}-secrets
                  key: DB_PASSWORD_APP

          volumeMounts:
            - name: migration-sql
              mountPath: /flyway/sql

      volumes:
        - name: migration-sql
          configMap:
            name: {{ include "cigg-app.fullname" . }}-db-migration-sql