apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cigg-app.fullname" . }}-db-migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: flyway
        image: {{ .Values.migration.image }}
        command: ["flyway"]
        args:
          - "-url={{ .Values.migration.jdbcUrl }}"
          - "-user={{ .Values.db.user }}"
          - "-password={{ .Values.db.password }}"
          - "-locations=filesystem:/flyway/sql"
          - "-connectRetries=60"
          - "migrate"

        volumeMounts:
        - name: migration-sql
          mountPath: /flyway/sql

      restartPolicy: OnFailure

      volumes:
      - name: migration-sql
        configMap:
          name: {{ include "cigg-app.fullname" . }}-db-migration-sql