apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cigg-app.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade   
  
type: Opaque
stringData:
  DB_USER: cigtracker
  DB_PASSWORD: password
  DB_USER_APP: cigtracker
  DB_PASSWORD_APP: password